obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.25, -0.145], [-0.25, 0.145], [0.25, 0.145], [0.25, -0.145]]

transform_tolerance: 0.5
resolution: 0.05 

static_map_layer:
    map_topic: map
    subscribe_to_updates: true

2d_obstacles_layer:
  observation_sources: scan
  scan: {data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true}

3d_obstacles_layer: 
  observation_sources: depth
  depth: {data_type: PointCloud2,
    topic: camera/depth/points,
    min_obstacle_height: 0.1,
    marking: true,
    clearing: true}

inflation_layer:
    inflation_radius: 2.0