global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0 
  publish_frequency: 0.5 
  static_map: true
  cost_scaling_factor: 10.0

  plugins:
    - {name: static_map_layer,    type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
    - {name: 2d_obstacles_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: 3d_obstacles_layer,  type: "costmap_2d::VoxelLayer"}
