mini_pupper_controller:
  type: "mini_pupper_trajopt/MiniPupperController"
  publish_rate: 250
  joints:
    - base_lf1
    - lf1_lf2
    - lf2_lf3
    - base_rf1
    - rf1_rf2
    - rf2_rf3
    - base_lb1
    - lb1_lb2
    - lb2_lb3
    - base_rb1
    - rb1_rb2
    - rb2_rb3
  constraints:
    goal_time: 0.0
    stopped_velocity_tolerance: 1.0

position_controller:
  type: "position_controllers/JointTrajectoryController"
  publish_rate: 250
  joints:
    - base_lf1
    - lf1_lf2
    - lf2_lf3
    - base_rf1
    - rf1_rf2
    - rf2_rf3
    - base_lb1
    - lb1_lb2
    - lb2_lb3
    - base_rb1
    - rb1_rb2
    - rb2_rb3
  constraints:
    goal_time: 0.0
    stopped_velocity_tolerance: 1.0